#!/bin/bash

function parse_git_branch {
  ref=$(git symbolic-ref HEAD 2> /dev/null) || return
  echo "("${ref#refs/heads/}")"
}

function proml {
  local BLUE="\[\033[0;34m\]"
  local RED="\[\033[0;31m\]"
  local LIGHT_RED="\[\033[1;31m\]"
  local GREEN="\[\033[0;32m\]"
  local LIGHT_GREEN="\[\033[1;32m\]"
  local WHITE="\[\033[1;37m\]"
  local LIGHT_GRAY="\[\033[0;37m\]"
  local YELLOW="\[\033[0;33m\]"
  local NONE="\[\033[0m\]"    
  case $TERM in
    xterm*)
      TITLEBAR='\[\033]0;\u@\h:\w\007\]'
    ;;
    *)
      TITLEBAR=""
    ;;
  esac

  PS1="\u: $RED\w$YELLOW\$(parse_git_branch)$NONE\$$NONE "
  PS2='> '
  PS4='+ '
}
proml

#
# cdworkspace tab completion
function cdworkspace { 
  cd ${HOME}/Documents/workspace/$1 
}

function _cdworkspace {
  local cur
  cur=${COMP_WORDS[COMP_CWORD]}
  COMPREPLY=( $(compgen -S/ -d ${HOME}/Documents/workspace/$cur | cut -b 37- ) )
}

complete -o nospace -F _cdworkspace cdworkspace

#
# Language Vers management initialization
eval "$(rbenv init -)"
eval "$(goenv init -)"
